article/urls.py
from django.conf.urls import url

from .views import (
    ArticleListView, 
    ArticleDetailView,
    ArticleListCategoryView,
    CreateArticleView,
    ManageArticle,
    DeleteArticle,
    UpdateArticle
)

urlpatterns = [
        url(r'^manage/update/(?P<pk>\d+)$', UpdateArticle.as_view(), name = 'update'),
        url(r'^manage/delete/(?P<pk>\d+)$', DeleteArticle.as_view(), name = 'delete'),    
        url('^manage/$',ManageArticle.as_view(), name='manage'),
        url(r'^create/$',CreateArticleView.as_view(), name = 'create'),
        url(r'^category/(?P<category>[\w]+)/(?P<page>\d+)$',ArticleListCategoryView.as_view(), name = 'category'),
        url(r'^(?P<page>\d+)$',ArticleListView.as_view(), name = 'list'),
        url(r'detail/(?P<slug>[\w-]+)$', ArticleDetailView.as_view(), name = 'detail'),
    ]

mywebsite/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from .views import MyWebsiteHome

urlpatterns = [
    url(r'^article/', include('article.urls', namespace='article')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', MyWebsiteHome.as_view(), name='home'),
]

article/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
# Create your models here.


class Category(models.Model):
    name        = models.CharField(max_length=255)
    description = models.TextField()
    published   = models.DateTimeField(auto_now_add=True)
    updated     = models.DateTimeField(auto_now=True) 
    slug        = models.SlugField(blank=True, editable=False)

    def save(self):
        self.slug = slugify(self.name)
        super().save()
    
    def get_absolute_url(self):
        url_slug = {'slug' : self.slug}
        return reverse('category:detail', kwargs = url_slug)
    
    def __str__(self):
        return "{}. {}".format(self.id, self.name)


class Article(models.Model):
    title       = models.CharField(max_length=255)
    body        = models.TextField()
    category    = models.ForeignKey(Category, on_delete=models.CASCADE)
    published   = models.DateTimeField(auto_now_add=True)
    updated     = models.DateTimeField(auto_now=True)
    slug        = models.SlugField(blank=True, editable=False)

    def save(self):
        self.slug = slugify(self.title)
        super().save()
    
    def get_absolute_url(self):
        url_slug = {'slug' : self.slug}
        return reverse('article:detail', kwargs = url_slug)


    def __str__(self):
        return "{}. {}".format(self.id, self.title)

article/forms.py
from django.forms import ModelForm 


from .models import Article 


class ArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = (
            'title',
            'body',
            'category',
        )

article/views.py
from django.shortcuts import render

# Create your views here.

from django.views.generic import (
	ListView, 
	DetailView, 
	CreateView, 
	DeleteView, 
	UpdateView
)
from django.urls import reverse_lazy

# load model
from .models import Article, Category

from .forms import ArticleForm

class UpdateArticle(UpdateView):
    form_class = ArticleForm
    model = Article
    template_name = 'article/article_update.html'

class DeleteArticle(DeleteView):
    model = Article
    template_name = 'article/article_delete_confirmation.html'
    success_url = reverse_lazy('article:manage')

class ManageArticle(ListView):
    model = Article
    template_name = 'article/article_manage.html'
    context_object_name = 'articles'

class CreateArticleView(CreateView):
    form_class = ArticleForm
    template_name = 'article/article_create.html'


class ArticleListCategoryView(ListView):
    model   = Article
    template_name = "article/article_category_list.html"
    context_object_name = "articl_list_category"
    ordering = ["-published"]
    model_category = Category
    paginate_by = 2
    def get_queryset(self):
        category_id = self.model_category.objects.filter(name=self.kwargs['category'])
        self.queryset = self.model.objects.filter(category = category_id[0].id)
        return super().get_queryset()

    def get_context_data(self, *args, **kwargs):
        
        categorys = self.model_category.objects.all().exclude(name=self.kwargs['category'])
        print(categorys)
        self.kwargs.update({'categorys' : categorys})
        kwargs = self.kwargs
        return super().get_context_data(*args,**kwargs)	



class ArticleListView(ListView):
    model = Article
    model_category = Category
    template_name = 'article/article_list.html'
    context_object_name = 'article_list'
    ordering = ['-published']
    paginate_by = 2
 
    def get_context_data(self, *args, **kwargs):
        
        categorys = self.model_category.objects.all()
        print(categorys)
        self.kwargs.update({'categorys' : categorys})
        kwargs = self.kwargs
        return super().get_context_data(*args,**kwargs)	
    

class ArticleDetailView(DetailView):
    model = Article
    template_name = 'article/article_detail.html'
    context_object_name = 'article'
    model_category = Category

    def get_context_data(self, *args, **kwargs):
        
        categorys = self.model_category.objects.all()
        print(self.object.category.id)
        
        self.kwargs.update({'categorys' : categorys})
        same_article = self.model.objects.filter(category=self.object.category.id).exclude(id=self.object.id)
        print(same_article)
        self.kwargs.update({'same_article' : same_article})
        kwargs = self.kwargs
        print (kwargs)
        return super().get_context_data(*args,**kwargs)	

class ArticlePerCateory():
    model_article = Article
    model_category = Category

    def get_latest_article_each_category(self):
        category_list = self.model_category.objects.all()
        queryset = []


        for category in category_list :

            article = self.model_article.objects.filter(category=category).latest('published')
            queryset.append(article)
        
        return queryset

mywebsite/views.py
from django.views.generic import TemplateView

from article.views import ArticlePerCateory


class MyWebsiteHome(TemplateView,ArticlePerCateory):
    template_name = 'index.html'

    def get_context_data(self):
        querysets = self.get_latest_article_each_category()

        context = {
            'last_article_list' : querysets
        }
        return context

article/templates/article/article_category_list.html
{% extends "base.html" %}


{% block page_title %}
    Article
{% endblock page_title %}
 


{% block contents %}
    <div class="row">
        <div class = "col-md-8">
                <h3>Category : {{category}}</h3>
                {% if is_paginated %}
                <nav aria-label="articlePage">
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                      <li class="page-item">
                        <a class="page-link" href="{% url 'article:category' category page_obj.previous_page_number%}">Previous</a>
                      </li>
                     {% else %}
                     <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1">Previous</a>
                      {% endif %} 
                     {% for page in paginator.page_range  %}
                    {% if page is page_obj.number %}
                    <li class="page-item active">
                            <span class="page-link" href="#">{{page}}<span class="sr-only">(current)</span></span>
                    </li>   
                    {% else %}
                    <li class="page-item">
                        <a class="page-link" href="{% url 'article:category' category page%}">{{page}}</a>
                    </li>   
                    {% endif %}
                     {% endfor %}
                      {% if page_obj.has_next %}
                      <li class="page-item">
                        <a class="page-link" href="{% url 'article:category' category page_obj.next_page_number%}">Next</a>
                      </li>
                     {% else %}
                     <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1">Next</a>
                      {% endif %} 
                    </ul>
                  </nav>
                  {% endif %}
                
                  {% for article in  articl_list_category%}
                <h3><a class = "text-dark" href="{% url 'article:detail' article.slug%}">{{article.title}}</a></h3>
                <h6>Published : {{article.published}}</h6>
                <p>{{article.body|truncatewords:150}}.. <a href="{% url 'article:detail' article.slug%}">Read More</a></p>  
                
                {% endfor %}
        </div>
        <div class = "col-sm">
            <h3>Category</h3>
            <ul class="list-group">
                    <li class="list-group-item"><a href="{% url 'article:list' 1%}">All Categorys</a></li>    
                {% for category in categorys  %}
                <li class="list-group-item"><a href="{% url 'article:category' category.name 1%}">{{category.name}}</a></li>    
                {% endfor %}
                    
                
            </ul>
        </div>
    </div>
        
    
{% endblock contents %}
    

article/templates/article/article_create.html
{% extends 'base.html' %}


{% block page_title %}
    Create
{% endblock page_title %}
 

{% block contents %}

<h3>Add Article</h3>
<form method="POST">
    {% csrf_token %}
        <!-- <table>
            {{form.as_table}}
        </table> -->
    <div class="form-group">
        <label for="{{form.title.id_for_label}}">{{form.title.label}} : </label>
        <input type="text" class="form-control" name = "{{form.title.name}}" maxlength="{{form.title.max}}" required id = "{{form.title.id_for_label}}"/> 
    </div>
    <div class="form-group">
        <label for="{{form.body.id_for_label}}">{{form.body.label}} : </label>
        <textarea name="{{form.body.name}}" rows="10" class="form-control" required id = "{{form.body.id_for_label}}"></textarea>
    </div>
    <div class="form-group col-md-4">
        <!-- {% for a in  form.category %}
        <h1>{{a}}</h1><br/>
        <h2>{{a.pk}}</h2><br/>
        <h3>{{a.value}}</h3><br/>
         {% endfor %} -->


    <label for="{{form.category.id_for_label}}">{{form.category.label}} : </label>
    <select name="{{form.category.name}}" required id="{{form.category.id_for_label}}" class="form-control">
        {% for a in  form.category %}
           <div>{{a}}</div>
        {% endfor %}
            
    </select>
</div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>
{% endblock contents %}

    

article/templates/article/article_delete_confirmation.html
{% extends 'base.html' %}

{% block page_title %}
    Delete Article
{% endblock page_title %}

{% block contents %}
    <h1>Delete article confirmation</h1>
    <p>Do you want to delete this article : </p>
    <h3>{{article.title}}</h3>
    <p>{{article.published}}</p>
    <form method='POST'>
        {% csrf_token %}
        <button type="submit" class="btn btn-outline-danger">Ya</button>
        <a class="btn btn-outline-primary" href="{%url 'article:manage'%}">No</a>
    </form>
{% endblock contents %}
    

    

article/templates/article/article_detail.html
{% extends 'base.html' %}


{% block page_title %}
    {{article.title}}
{% endblock page_title %}
    

{% block contents %}
<div class="row">
	<div class="col-md-8">
		<h1>{{article.title}}</h1>
		<h5>Category : {{article.category}} | {{article.published}}</h5>
		<p>{{article.body}}</p>	
	</div>
	<div class="col-sm">
		<h3>Category</h3>
		<ul class="list-group">
				<li class="list-group-item"><a href="{% url 'article:list' 1%}">All Categorys</a></li>    
			{% for category in categorys  %}
			<li class="list-group-item"><a href="{% url 'article:category' category.name 1%}">{{category.name}}</a></li>    
			{% endfor %}
				
			
		</ul>
		<h3>The Same Articles</h3>

		<ul class="list-group">
			
			{% for article in same_article  %}
			<li class="list-group-item"><a href="{% url 'article:detail' article.slug%}">{{article.title}}</a></li>    
			{% endfor %}
				
			
		</ul>

	</div>
</div>
{% endblock contents %}
    

article/templates/article/article_list.html
{% extends "base.html" %}


{% block page_title %}
    Article
{% endblock page_title %}
 


{% block contents %}
    <div class="row">
        <div class = "col-md-8">
                {% if is_paginated %}
                <nav aria-label="articlePage">
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                      <li class="page-item">
                        <a class="page-link" href="{% url 'article:list' page_obj.previous_page_number%}">Previous</a>
                      </li>
                     {% else %}
                     <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1">Previous</a>
                      {% endif %} 
                     {% for page in paginator.page_range  %}
                    {% if page is page_obj.number %}
                    <li class="page-item active">
                            <span class="page-link" href="#">{{page}}<span class="sr-only">(current)</span></span>
                    </li>   
                    {% else %}
                    <li class="page-item">
                        <a class="page-link" href="{% url 'article:list' page%}">{{page}}</a>
                    </li>   
                    {% endif %}
                     {% endfor %}
                      {% if page_obj.has_next %}
                      <li class="page-item">
                        <a class="page-link" href="{% url 'article:list' page_obj.next_page_number%}">Next</a>
                      </li>
                     {% else %}
                     <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1">Next</a>
                      {% endif %} 
                    </ul>
                  </nav>
                  {% endif %}
                
                  {% for article in  article_list%}
                <h3><a class = "text-dark" href="{% url 'article:detail' article.slug%}">{{article.title}}</a></h3>
                <h6>Category : {{article.category.name}} | Published : {{article.published}}</h6>
                <p>{{article.body|truncatewords:150}}.. <a href="{% url 'article:detail' article.slug%}">Read More</a></p>  
                
                {% endfor %}
        </div>
        <div class = "col-sm">
            <h3>Category</h3>
            <ul class="list-group">
                {% for category in categorys  %}
                <li class="list-group-item"><a href="{% url 'article:category' category.name 1%}">{{category.name}}</a></li>    
                {% endfor %}
                    
                
            </ul>
        </div>
    </div>
        
    
{% endblock contents %}
    

article/templates/article/article_manage.html
{% extends 'base.html' %}


{% block page_title %}
    Manage Article
{% endblock page_title %}


{% block contents %}
    <h1>Manage Article</h1>
    <div  style="float : right; padding-bottom : 20px;" >
          <a class="btn btn-primary" href="{%url 'article:create' %}">Create</a>
    </div>
    <table class="table">
        <thead class="thead-dark">
          <tr>
            <th scope="col">#</th>
            <th scope="col">Title</th>
            <th scope="col">Category</th>
            <th scope="col">Published</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
            
            {% for article in articles  %}
            <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td>{{article.title}}</td>
                <td>{{article.category.name}}</td>
                <td>{{article.published}}</td>
                <td>
                    <a class="btn btn-warning" href="{%url 'article:update' article.id%}">Edit</a>
                    <a  class="btn btn-danger" href="{%url 'article:delete' article.id%}">Delete</a>
                </td>
              </tr>
            {% endfor %}
        </tbody>
      </table>
{% endblock contents %}
    

article/templates/article/article_update.html
{% extends 'base.html' %}


{% block page_title %}
    Create
{% endblock page_title %}
 

{% block contents %}

<h3>Add Article</h3>
<form method="POST">
    {% csrf_token %}
        <!-- <table>
            {{form.as_table}}
        </table> -->
    <div class="form-group">
        <label for="{{form.title.id_for_label}}">{{form.title.label}} : </label>
        <input type="text" class="form-control" name = "{{form.title.name}}" maxlength="{{form.title.max}}" 
        required id = "{{form.title.id_for_label}}" value="{{form.title.value}}"/> 
    </div>
    <div class="form-group">
        <label for="{{form.body.id_for_label}}">{{form.body.label}} : </label>
        <textarea name="{{form.body.name}}" rows="10" class="form-control" 
        required id = "{{form.body.id_for_label}}">{{form.body.value}}</textarea>
    </div>
    <div class="form-group col-md-4">
    <label for="{{form.category.id_for_label}}">{{form.category.label}} : </label>
    <select name="{{form.category.name}}" required id="{{form.category.id_for_label}}" class="form-control">
        {% for a in  form.category %}
           <div>{{a}}</div>
        {% endfor %}
            
    </select>
</div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>
{% endblock contents %}

    

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>
		{% block page_title %}
			
		{% endblock page_title %}
	</title>
	{% include "snippets/styles.html" %}
</head>
<body>
	{% include "snippets/navbar.html" %}

	<div class="container" style="margin-top:100px">
		{% block contents %}
		
		{% endblock contents %}
	</div>

	{% include "snippets/scripts.html" %}
</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block page_title %}
	Home
{% endblock page_title %}


{% block contents %}
	<h1>Home</h1>
	<div class="row" >
		{% for article in last_article_list %}
			<div class="col-sm-4" style ="padding-bottom: 20px !important;">
				<div class="card" >
				  <div class="card-body">
				  <h5 class="card-title"><a href="{% url 'article:category' article.category.name 1%}">{{article.category.name}}</a></h5>
				    <h6 class="card-subtitle mb-2"><a class = "text-dark" href="{% url 'article:detail' article.slug%}">{{article.title}}</a></h6>
				    
				    <p class="card-text">{{article.body|truncatewords:10}}</p>
				    
				  </div>
				</div>
			</div>
		{% endfor %}
	</div>
	

	

	
{% endblock contents %}

templates/snippets/navbar.html
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
  <!-- <div class="container"> -->
	  <a class="navbar-brand" href="{% url 'home' %}">BLOG</a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>
	  <div class="collapse navbar-collapse" id="navbarNavDropdown">
	    <ul class="navbar-nav">
	      <li class="nav-item">
	        <a class="nav-link" href="{% url 'home' %}">Home</a>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link" href="{% url 'article:list' 1%}">Artikel</a>
	      </li>
	    </ul>
	    <div class="nav-item dropdown ml-auto">
	        <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	          User
	        </a>
	        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
	          <a class="dropdown-item" href="{%url 'article:create' %}">Add Article</a>
	          <a class="dropdown-item" href="{%url 'article:manage' %}">Manage Article</a>
	          
	        </div>
	    </div>
	  </div>
  <!-- </div> -->
</nav>

templates/snippets/scripts.html
{% load static %}
<script src="{% static 'vendor/jquery/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'vendor/popper/popper.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

templates/snippets/styles.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">